<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt #{{ $receipt->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; margin: 20px; }
        .header { text-align: center; }
        .details { margin-top: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: left; }
        .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #555; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Transport Department - Tire Request Receipt</h2>
        <p>Receipt ID: #{{ $receipt->id }}</p>
        <p>Date: {{ $receipt->created_at->format('Y-m-d') }}</p>
    </div>

    <div class="details">
        <h3>Supplier Details</h3>
        <p><strong>Name:</strong> {{ $receipt->supplier->name ?? 'N/A' }}</p>
        <p><strong>Address:</strong> {{ $receipt->supplier->address ?? 'N/A' }}</p>
        <p><strong>Contact:</strong> {{ $receipt->supplier->contact_no ?? 'N/A' }}</p>

        <h3>Vehicle & Request Details</h3>
        <p><strong>Vehicle Plate:</strong> {{ $receipt->tireRequest->vehicle->plate_number ?? 'N/A' }}</p>
        <p><strong>Tire Count:</strong> {{ $receipt->tireRequest->tire_count ?? 'N/A' }}</p>
        <p><strong>Description:</strong> {{ $receipt->description ?? 'N/A' }}</p>

        <h3>Amount</h3>
        <p><strong>Total:</strong> Rs. {{ number_format($receipt->amount, 2) }}</p>
    </div>

    <div class="footer">
        <p>Generated by Transport Officer | © {{ date('Y') }}</p>
    </div>
</body>
</html>
