<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Receipt #{{ $receipt->id }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 40px;
            color: #333;
            background-color: #fff;
        }

        .header {
            text-align: center;
            border-bottom: 2px solid #0056b3;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .logo {
            width: 100px;
            margin-bottom: 10px;
        }

        .title {
            color: #0056b3;
            font-size: 22px;
            margin: 0;
        }

        .receipt-meta {
            font-size: 13px;
            color: #555;
        }

        .section-title {
            background-color: #f2f2f2;
            padding: 8px;
            border-left: 4px solid #0056b3;
            font-weight: bold;
            margin-top: 25px;
            font-size: 15px;
        }

        .details p {
            margin: 4px 0;
            font-size: 13px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }

        th, td {
            border: 1px solid #bbb;
            padding: 10px;
            text-align: left;
            font-size: 13px;
        }

        th {
            background-color: #f8f8f8;
        }

        .amount {
            font-size: 16px;
            font-weight: bold;
            color: #0056b3;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 11px;
            color: #777;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .signature-section {
            margin-top: 50px;
            display: flex;
            justify-content: space-between;
            font-size: 13px;
        }

        .signature {
            text-align: center;
            width: 45%;
        }

        .signature-line {
            border-top: 1px solid #000;
            margin-top: 40px;
            width: 80%;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div class="header">
    <h2 class="title">Transport Department - Tyre Request Receipt</h2>
        <p class="receipt-meta">
            <strong>Receipt ID:</strong> #{{ $receipt->id }}<br>
            <strong>Date:</strong> {{ $receipt->created_at->format('Y-m-d') }}
        </p>
    </div>

    <div class="details">
        <div class="section-title">Supplier Details</div>
        <p><strong>Name:</strong> {{ $receipt->supplier->name ?? 'N/A' }}</p>
        <p><strong>Address:</strong> {{ $receipt->supplier->address ?? 'N/A' }}</p>
        <p><strong>Contact:</strong> {{ $receipt->supplier->contact_no ?? 'N/A' }}</p>

        <div class="section-title">Vehicle & Request Details</div>
        <p><strong>Vehicle Plate:</strong> {{ $receipt->tireRequest->vehicle->plate_number ?? 'N/A' }}</p>
    <p><strong>Tyre Count:</strong> {{ $receipt->tireRequest->tire_count ?? 'N/A' }}</p>
        <p><strong>Description:</strong> {{ $receipt->description ?? 'N/A' }}</p>

        <div class="section-title">Amount</div>
        <table>
            <tr>
                <th>Description</th>
                <th>Amount (Rs.)</th>
            </tr>
            <tr>
                <td>{{ $receipt->description ?? 'N/A' }}</td>
                <td class="amount">{{ number_format($receipt->amount, 2) }}</td>
            </tr>
        </table>

        <div class="signature-section">
            <div class="signature">
                <div class="signature-line"></div>
                <p>Supplier Signature</p>
            </div>
            <div class="signature">
                <div class="signature-line"></div>
                <p>Transport Officer Signature</p>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>Generated by <strong>Transport Officer</strong> | © {{ date('Y') }} Transport Department</p>
        <p>This document was generated electronically and is valid without signature.</p>
    </div>
</body>
</html>
